# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'myTestProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for myTestProject
  pod 'RNMobileCenterShared', '~> 0.10.0'

  

  target 'myTestProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'myTestProject-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for myTestProject-tvOS

  target 'myTestProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
